### ISSUE TITLE
challonge widget not producing anything

### ISSUE THREAD

**Issue by mirnhoj** [farpenoodle/StreamControl#10]
using streamcontrol 0.4b (http://farpnut.net/download/StreamControl_0_4b.7z) and using the example on https://ajclarke.github.io/StreamControl/challonge.html produces no widget even after entering all the necessary info in widget settings. has the challonge widget been implemented in the aforementioned version, or do i need to compile the latest commit of streamcontrol for myself?

**Comment by farpenoodle** [comment]
I believe you need to compile it. The beta version isn't up to the latest
commit.

**Comment by mirnhoj** [comment]
thanks, compiling from source made the challonge widget appear.
