### ISSUE TITLE
Fixed minimal sized window 

### ISSUE THREAD

**Issue by rXp** [farpenoodle/StreamControl#17]
When I launch StreamControl I get the tiniest of window that I cannot resize.
I work with a res of 2736x1824, this might be the problem.
![2016-02-22 15_28_59-](https://cloud.githubusercontent.com/assets/1590264/13220927/055b5812-d979-11e5-9ce1-6679cbbcb8aa.png)

**Comment by farpenoodle** [comment]
This is more a problem with DPI scaling than anything.  Try put this .bat file in the same directory as the executable and running that. The fix already in version control. But doesn't really work so well with odd scaling factors that aren't multiples of 1. Such as 1.5. Let me know if that fixes the problem for you.

[hidpi.zip](https://github.com/farpenoodle/StreamControl/files/141014/hidpi.zip)

**Comment by rXp** [comment]
Yes thank you, it fixed it.
