### ISSUE TITLE
New version for High DPI displays

### ISSUE THREAD

**Issue by thomas-vt** [farpenoodle/StreamControl#21]
Running into similar issue as https://github.com/farpenoodle/StreamControl/issues/17

Would it be possible to have newer version exe (for Windows) available on your website with fix.

**Comment by thomas-vt** [comment]
Was able to compile. Compilation instructions below,

1. Install QtCreator (qt-unified-windows-x86-2.0.5-1-online.exe) - http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe

2. Install MinGW - https://sourceforge.net/projects/mingw/files/ - mingw-get-setup.exe (Install MSYS, Basic and C++)

3. Add path to env 
eg:
D:\Qt\5.8\mingw53_32\bin;D:\MinGW\bin;D:\MinGW\msys\1.0\bin

4. Download Streamcontrol from Github

5. cd D:\StreamControl\StreamControl-master\StreamControl-master\StreamControl (location of StreamControl.pro)
qmake && make (exe is generated in release subfolder)

**Comment by KamiMelee** [comment]
I'm still struggling to get it to compile. I'm getting this when I execute qmake && make

make -f Makefile.Release
make[1]: Entering directory `/c/Users/UserName/Downloads/StreamControl-master/StreamControl-master/StreamControl'
Makefile.Release:247: *** missing separator.  Stop.
make[1]: Leaving directory `/c/Users/UserName/Downloads/StreamControl-master/StreamControl-master/StreamControl'
make: *** [release] Error 2

Any way you'd be able to upload a zip of your compiled version? :)
