### ISSUE TITLE
A way to interact with the controls from other software

### ISSUE THREAD

**Issue by neoyagami** [farpenoodle/StreamControl#29]
Hi.
 I use streamcontrol a lot, and I wondered if I colud add buton to my streamdeck to add values to the scores, in that way a dont need to open the wndows and just press my "game for player one" and "game for player 2" in my streamdeck

I tried using pywinauto to automate the interaction but looks pywinauto cannot see the controls inside the streamcontrol window, 
is there way to interact with the controls from outside?, It will make my stream easier to handle especially when is me the one playing 

The only thing that is left is reading the xml directly and adding values to the scores, but that is not elegant at all.

Thanks in advance (sorry for my bad gammar)

**Comment by farpenoodle** [comment]
Hello! So one thing you could try is assign hotkeys. Unfortunately I don't think you can change the value of items by themselves but if you use a spinbox widget you can use the increaseHotkey and decreaseHotkey parameters to create hotkeys to increase or decrease the value. So for example:

`<spinBox id="pScore1" x="250" y="10" width="42" height="22" maximum="999" increaseHotkey="ctrl+1" decreaseHotkey="ctrl+2" />`

Then you assign those to streamdeck and it should work.

**Comment by neoyagami** [comment]
thanks !! 
do this work on the 0.3 version or i need the beta version?

**Comment by neoyagami** [comment]
Hi. looks like is a 0.4 version feature  and works nice. now  the values are update nicely, 
is thera a way to save the scores? bc the hotkey just change the value in the sinbox. but I cannot find a option to save the scores

**Comment by neoyagami** [comment]
Had to lookup in the code for all the tags 
found if I do this
     <button id="tst" type="setButton" x="390" y="5" width="20" saveonclick="1"  height="20" hotkey="ctrl+shift+s"   >save?</button>
this button works as a save button 
thanks for this nice little piece of software :)
